kind: pipeline
type: kubernetes
name: default

steps:

- name: build
  image: node:14
  commands:
    - "npm build"

- name: publish  
  image: plugins/ecr
  settings:
    access_key: 
      from_secret: aws_access_key
    secret_key: 
      from_secret: aws_secret_key
    repo: 
      from_secret: aws_ecr_repo
    registry: 
      from_secret: aws_ecr_registry
    region:
      from_secret: aws_region
    tags:
        - 'latest'
