kind: pipeline
name: test slack

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run build
  - npm start

- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
